export const CONSTANTES = {
  GET_PRODUCTS: "GET_PRODUCTS",
  GET_ID: "GET_ID",
  SEARCH_NAME: "SEARCH_NAME",
  FILTER_BY_CATEGORYS: "FILTER_BY_CATEGORYS",
  ORDER_PRICE: "ORDER_PRICE",
  RECETA_CREADA: "PRODUCT_CREADA",
  RECETA_NO_CREADA: "PRODUCT_NO_CREADA",
  ADD_TO_CART: "ADD_TO_CART",
  DELETE_ONE_PRODUCT: "DELETE_ONE_PRODUCT",
  CLEAR_CART: "CLEAR_CART",
  DELETE_ALL_PRODUCT: "DELETE_ALL_PRODUCT",
};
